---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-test-script
data:
  write.sh: |
{{ .Files.Get "scripts/test_write.sh" | indent 4}}
  read.sh: |
{{ .Files.Get "scripts/test_read.sh" | indent 4}}