nameOverride: ""

image:
  repository: kloeckneri/db-operator
  tag: latest
  pullPolicy: Always

# imagePullSecrets:
#   - name: myRegistrySecret

reconcileInterval: "60"

rbac:
  create: true

serviceAccount:
  create: true

resources: {}

nodeSelector: {}

annotations: {}

affinity: {}

tolerations: []

config:
  instance:
    google:
      proxy:
        nodeSelector: {}
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
    generic: {}
    percona:
      proxy:
        image: severalnines/proxysql:2.0
        configTemplate: |-
          datadir="/var/lib/proxysql"

          admin_variables=
          {
              mysql_ifaces="0.0.0.0:6032"
              refresh_interval=2000
              web_enabled=false
              web_port=6080
              stats_credentials="stats:admin"
          }

          mysql_variables=
          {
              threads=4
              max_connections=2048
              default_query_delay=0
              default_query_timeout=36000000
              have_compress=true
              poll_timeout=2000
              interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
              default_schema="information_schema"
              stacksize=1048576
              server_version="5.7.28"
              connect_timeout_server=10000
              monitor_history=60000
              monitor_connect_interval=200000
              monitor_ping_interval=200000
              ping_interval_server_msec=10000
              ping_timeout_server=200
              commands_stats=true
              sessions_sort=true
              monitor_username="$MONITOR_USERNAME"
              monitor_password="$MONITOR_PASSWORD"
              monitor_galera_healthcheck_interval=2000
              monitor_galera_healthcheck_timeout=800
          }

          mysql_galera_hostgroups =
          (
              {
                  writer_hostgroup=10
                  backup_writer_hostgroup=20
                  reader_hostgroup=30
                  offline_hostgroup=9999
                  max_writers=2
                  writer_is_also_reader=2
                  max_transactions_behind=30
                  active=1
              }
          )

          mysql_servers =
          (
            {{- range . }}
              { address="{{.Host}}", port={{.Port}}, hostgroup=10, max_connections={{.MaxConn}} },
            {{- end }}
          )

          mysql_query_rules =
          (
              {
                  rule_id=100
                  active=1
                  match_pattern="^SELECT .* FOR UPDATE"
                  destination_hostgroup=10
                  apply=1
              },
              {
                  rule_id=200
                  active=1
                  match_pattern="^SELECT .*"
                  destination_hostgroup=20
                  apply=1
              },
              {
                  rule_id=300
                  active=1
                  match_pattern=".*"
                  destination_hostgroup=10
                  apply=1
              }
          )
        # do not remove this empty line above
  backup:
    nodeSelector: {}
    postgres:
      image: "kloeckneri/pgdump-gcs:latest"
    mysql:
      image: "kloeckneri/mydump-gcs:latest"
  monitoring:
    nodeSelector: {}
    postgres:
      image: wrouesnel/postgres_exporter:latest
      queries:
        pg_stat_statements:
          query: "SELECT userid, pgss.dbid, pgdb.datname, queryid, query, calls, total_time, mean_time, rows FROM pg_stat_statements pgss LEFT JOIN (select oid as dbid, datname from pg_database) as pgdb on pgdb.dbid = pgss.dbid WHERE not queryid isnull ORDER BY mean_time desc limit 20"
          metrics:
            - userid:
                usage: "LABEL"
                description: "User ID"
            - dbid:
                usage: "LABEL"
                description: "database ID"
            - datname:
                usage: "LABEL"
                description: "database NAME"
            - queryid:
                usage: "LABEL"
                description: "Query unique Hash Code"
            - query:
                usage: "LABEL"
                description: "Query class"
            - calls:
                usage: "COUNTER"
                description: "Number of times executed"
            - total_time:
                usage: "COUNTER"
                description: "Total time spent in the statement, in milliseconds"
            - mean_time:
                usage: "GAUGE"
                description: "Mean time spent in the statement, in milliseconds"
            - rows:
                usage: "COUNTER"
                description: "Total number of rows retrieved or affected by the statement"

secrets:
  gsql: {}