apiVersion: v1
entries:
  db-instances:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.992748+02:00"
    description: Database Instances for db operator
    digest: b039af38554da0fc8037b16397d49757d2c0b1a9e652867309df81b45950f375
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.992512+02:00"
    description: Database Instances for db operator
    digest: 3593c0f28606ed4ee028d779ce70b23e257f85d8c96f93449ed4deb25bcea208
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.992029+02:00"
    description: Database Instances for db operator
    digest: 6abeb95a030681041d41bb416624846819a7fb284a1f9b8cd8ef00d4517343e4
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.991531+02:00"
    description: Database Instances for db operator
    digest: ba545b09123c5cf0276da24cf16fcaeae1d51a92e253731768b35478fb0294f4
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.99106+02:00"
    description: Database Instances for db operator
    digest: 0a9f5c620c9ee8d8e33ea96f797be989efab296fbeeca24e26c84fdb2136d704
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.1.0.tgz
    version: 0.1.0
  db-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.995848+02:00"
    description: A Database Operator
    digest: 7022f5c9cf4e1704bc06dafc4f3dfc662421b2ecb918eed0b0a601acca860bc9
    name: db-operator
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-operator-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.995516+02:00"
    description: A Database Operator
    digest: a00294defa1914f326b363c1cb0d36b22297fefd71e72a83510c70a1a8020d31
    name: db-operator
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-operator-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.994767+02:00"
    description: A Database Operator
    digest: d2d2a7f6b7913585283d72cea95770067e6c9625479e349c2e18b7dc3fbd3a52
    name: db-operator
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-04T11:04:09.993578+02:00"
    description: A Database Operator
    digest: 6f41f18fe10b74edaec021defdcca99e2c65b5ed60b3c53b3d7ee7b124ccfeb0
    name: db-operator
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-04T11:04:09.990427+02:00"
