apiVersion: v1
entries:
  db-instances:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T12:58:15.707145+01:00"
    description: Database Instances for db operator
    digest: 0a9f5c620c9ee8d8e33ea96f797be989efab296fbeeca24e26c84fdb2136d704
    name: db-instances
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-instances-0.1.0.tgz
    version: 0.1.0
  db-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T12:58:15.708725+01:00"
    description: A Database Operator
    digest: 6f41f18fe10b74edaec021defdcca99e2c65b5ed60b3c53b3d7ee7b124ccfeb0
    name: db-operator
    urls:
    - https://kloeckner-i.github.io/db-operator/helm/db-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-24T12:58:15.705135+01:00"
